version: '3.5'

services:
  template:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/server/template/microservice-template}:${IMAGE_TAG:-latest}
    environment:
      - PORT
      - MICROSERVICE_NAME
      - SPRING_PROFILES_ACTIVE
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - metric-net
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: PathPrefix:/api/${MICROSERVICE_NAME}
        traefik.backend: ${MICROSERVICE_NAME}
        traefik.port: '${PORT}'
      restart_policy:
        delay: 10s
        window: 3m

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
